{% set name = "openbabel" %}
{% set version = "3.1.0" %}
{% set sha256 = "0b28f5326383339e454fae3e1d69152f30956ee9e87119d56d03970c3b5346f1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openbabel/openbabel/archive/openbabel-{{ version|replace('.','-') }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - fix_library_path_search.diff
    - fix_data_path.diff
    - fix_babel_test_paths.diff
    - fix_backinserter.diff

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - swig
  host:
    - python
    - zlib
    - eigen
    - libxml2
    - cairo
    - rapidjson
  run:
    - python

test:
  imports:
    - openbabel.openbabel
    - openbabel.pybel
  commands:
    - obabel --help
    - obabel -:c1ccccc1 --gen3d -omol2
    - obabel -:c1ccccc1 --gen3d -oinchi
    - obabel -:c1ccccc1 -opng -O img.png

about:
  home: http://openbabel.org/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: A chemical toolbox designed to speak the many languages of chemical data
  description: |
    Open Babel is a chemical toolbox designed to speak the many languages of chemical
    data. It's an open, collaborative project allowing anyone to search, convert,
    analyze, or store data from molecular modeling, chemistry, solid-state materials,
    biochemistry, or related areas.
  doc_url: http://openbabel.org/
  dev_url: https://github.com/openbabel/openbabel

extra:
  recipe-maintainers:
    - njzjz
    - mcs07
    - mwojcikowski
    - fredrikw
