build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
provider:
  win: azure
  linux_ppc64le: azure
  linux_aarch64: azure
test_on_native_only: true
github:
  branch_name: main
  tooling_branch_name: main
